  spring:
     datasource:
       username: 'sa'
       url: 'jdbc:h2:file:/home/pawelwit/work/organizer/organizerDb2'
     h2.console:
          enabled: true
          path: '/console'
     main:
       banner-mode: off
     jpa:
       database-platform: 'org.hibernate.dialect.H2Dialect'
       hibernate:
         ddl-auto: validate
     flyway:
       baseline-on-migrate: true
  task.template.allowMultipleTasksFromTemplate: false
  management:
    endpoints:
      web:
        base-path: '/info'
        exposure:
          include: '*'





